# Decision Tree Optimization

In [1]:
import pandas as pd
import json

In [2]:
df = pd.DataFrame({'studied': [1,2,3,4,5,6,7,8,9,10,11,12], 
        'passed': [0,0,0,0,1,1,1,1,1,1,1,1]})

In [3]:
df

,studied,passed
0,1,0
1,2,0
2,3,0
3,4,0
4,5,1
5,6,1
6,7,1
7,8,1
8,9,1
9,10,1


## Mid point

In [4]:
# compute mid points between values of studied
mid_points = []
for i in range(len(df['studied']) - 1):
    mid_point = (df['studied'][i] + df['studied'][i+1]) / 2
    # [i] refer to the fist value and [i+1] refer to the second value and so on
    print(mid_point)
    mid_points.append(mid_point)

1.5
2.5
3.5
4.5
5.5
6.5
7.5
8.5
9.5
10.5
11.5


In [8]:
x = df['studied'].values
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
print("from 1st item to 2nd last:")
print(x[:-1])
print("from 2nd item to last:")
print(x[1:])

from 1st item to 2nd last:
[ 1  2  3  4  5  6  7  8  9 10 11]
from 2nd item to last:
[ 2  3  4  5  6  7  8  9 10 11 12]


In [13]:
mid_points = (x[:-1] + x[1:]) / 2
print(mid_points)

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5]


## Sliding Windows

### Gini Formula

In [35]:
def gini(y):
    if len(y) == 0:
        return 0
    p0 = (y == 0).sum() / len(y)
    p1 = (y == 1).sum() / len(y)
    gini = 1 - (p0**2 + p1**2)
    return gini

In [36]:
# test gini
gini(df['passed'].values)

np.float64(0.4444444444444444)

In [37]:
def weighted_gini(y_left, y_right):
    n = len(y_left) + len(y_right)
    gini_left = gini(y_left)
    gini_right = gini(y_right)
    weighted_gini = (len(y_left) / n) * gini_left + (len(y_right) / n) * gini_right
    return weighted_gini

In [39]:
def weighted_gini_new(y_left, y_right):
    n = len(y_left) + len(y_right)

    if n == 0:
        return 0
    
    if len(y_left) == 0:
        p0_left = 0
        p1_left = 0
    else:
        p0_left = (y_left == 0).sum() / len(y_left)
        p1_left = (y_left == 1).sum() / len(y_left)

    if len(y_right) == 0:
        p0_right = 0
        p1_right = 0
    else:
        p0_right = (y_right == 0).sum() / len(y_right)
        p1_right = (y_right == 1).sum() / len(y_right)

    weighted_gini = (len(y_left) / n) * (1 - (p0_left**2 + p1_left**2)) + (len(y_right) / n) * (1 - (p0_right**2 + p1_right**2))
    return weighted_gini


In [40]:
# Split base on first mid point
mid_point = mid_points[0]
left_node = df[df['studied'] <= mid_point]
right_node = df[df['studied'] > mid_point]

In [41]:
print(mid_point)
print(left_node)
print(right_node)

1.5
   studied  passed
0        1       0
    studied  passed
1         2       0
2         3       0
3         4       0
4         5       1
5         6       1
6         7       1
7         8       1
8         9       1
9        10       1
10       11       1
11       12       1


In [ ]:
weighted_gini_second = weighted_gini(left_node['passed'].values, right_node['passed'].values)

In [24]:
# second mid point split
mid_point = mid_points[1]
left_node = df[df['studied'] <= mid_point]
right_node = df[df['studied'] > mid_point]
weighted_gini_second = weighted_gini(left_node['passed'].values, right_node['passed'].values)
weighted_gini_new_second = weighted_gini_new(left_node['passed'].values, right_node['passed'].values)

In [25]:
print("Weighted Gini for first split:", weighted_gini_first)
print("Weighted Gini for second split:", weighted_gini_second)

Weighted Gini for first split: 0.36363636363636365
Weighted Gini for second split: 0.26666666666666655


In [26]:
print("Weighted Gini for first split:", weighted_gini_new_first)
print("Weighted Gini for second split:", weighted_gini_new_second)

Weighted Gini for first split: 0.36363636363636365
Weighted Gini for second split: 0.26666666666666655


## Sliding Windows